name: Build push and deploy

on:
  push:
    branches: 
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/booking

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build image
        run: make build
      
      - name: "Push to GCR"
        run: |
        docker tag booking:${GITHUB_SHA::7} $IMAGE_NAME:${GITHUB_SHA::7}
        docker push ${IMAGE_NAME}:${GITHUB_SHA::7}

        docker tag ${IMAGE_NAME}:${GITHUB_SHA::7} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}:latest